import java.awt.Cursor;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.JOptionPane;
import javax.swing.ImageIcon;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Maryann
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    
    //Object Declaration
    private final Database dataobj=new Database();
    
    
    private int attempts=0;//Declare and initialize variable to store incorrect attempts
    
    
    
    
    public Login() {
        initComponents();
        setTitle("Login");//Set window title
        setDefaultCloseOperation(this.DO_NOTHING_ON_CLOSE);//Prevent system shutdown from clicking 'X' button
        
        //Set Icon
        logo_label.setIcon(dataobj.CreateIcon(logo_label));
        
        //Hide error messages
        accnum_error.setVisible(false);
        pin_error.setVisible(false);
        
        
        
        
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        body_panel = new javax.swing.JPanel();
        accnum_label = new javax.swing.JLabel();
        pin_label = new javax.swing.JLabel();
        login_button = new javax.swing.JButton();
        signup_button = new javax.swing.JButton();
        back_button = new javax.swing.JButton();
        accnum_error = new javax.swing.JLabel();
        pin_error = new javax.swing.JLabel();
        accnum_field = new javax.swing.JTextField();
        forgotaccnum_button = new javax.swing.JButton();
        forgotaccnum_button.setBorder(null);
        forgotaccnum_button.setContentAreaFilled(false);
        pin_field = new javax.swing.JPasswordField();
        header_panel = new javax.swing.JPanel();
        header_label = new javax.swing.JLabel();
        logo_label = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        body_panel.setBackground(new java.awt.Color(115, 115, 115));

        accnum_label.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        accnum_label.setForeground(new java.awt.Color(35, 35, 35));
        accnum_label.setText("Account Number:");

        pin_label.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        pin_label.setForeground(new java.awt.Color(35, 35, 35));
        pin_label.setText("PIN:");

        login_button.setBackground(new java.awt.Color(121, 81, 168));
        login_button.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        login_button.setForeground(new java.awt.Color(35, 35, 35));
        login_button.setText("LOGIN");
        login_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login_buttonActionPerformed(evt);
            }
        });

        signup_button.setBackground(new java.awt.Color(121, 81, 168));
        signup_button.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        signup_button.setForeground(new java.awt.Color(35, 35, 35));
        signup_button.setText("SIGN UP");
        signup_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signup_buttonActionPerformed(evt);
            }
        });

        back_button.setBackground(new java.awt.Color(121, 81, 168));
        back_button.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        back_button.setForeground(new java.awt.Color(35, 35, 35));
        back_button.setText("BACK");
        back_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_buttonActionPerformed(evt);
            }
        });

        accnum_error.setForeground(new java.awt.Color(154, 22, 22));
        accnum_error.setText("Missing Value");

        pin_error.setForeground(new java.awt.Color(154, 22, 22));
        pin_error.setText("Missing Value");

        accnum_field.setBackground(new java.awt.Color(152, 152, 152));

        forgotaccnum_button.setBackground(new java.awt.Color(121, 81, 168));
        forgotaccnum_button.setForeground(new java.awt.Color(154, 22, 22));
        forgotaccnum_button.setText("Forgot Account Number?");
        forgotaccnum_button.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        forgotaccnum_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                forgotaccnum_buttonActionPerformed(evt);
            }
        });

        pin_field.setBackground(new java.awt.Color(152, 152, 152));

        javax.swing.GroupLayout body_panelLayout = new javax.swing.GroupLayout(body_panel);
        body_panel.setLayout(body_panelLayout);
        body_panelLayout.setHorizontalGroup(
            body_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(body_panelLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(body_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pin_field)
                    .addComponent(accnum_label)
                    .addComponent(pin_label)
                    .addGroup(body_panelLayout.createSequentialGroup()
                        .addComponent(login_button, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                        .addComponent(signup_button))
                    .addComponent(accnum_field)
                    .addComponent(pin_error, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(accnum_error, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(forgotaccnum_button)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, body_panelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(back_button, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );
        body_panelLayout.setVerticalGroup(
            body_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(body_panelLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(accnum_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(body_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(accnum_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(forgotaccnum_button))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(accnum_error)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pin_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pin_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pin_error)
                .addGap(43, 43, 43)
                .addGroup(body_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(login_button, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(signup_button))
                .addGap(18, 18, 18)
                .addComponent(back_button)
                .addGap(51, 51, 51))
        );

        header_panel.setBackground(new java.awt.Color(105, 54, 158));

        header_label.setFont(new java.awt.Font("Corbel", 1, 36)); // NOI18N
        header_label.setForeground(new java.awt.Color(204, 204, 204));
        header_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        header_label.setText("Login");
        header_label.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout header_panelLayout = new javax.swing.GroupLayout(header_panel);
        header_panel.setLayout(header_panelLayout);
        header_panelLayout.setHorizontalGroup(
            header_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(header_panelLayout.createSequentialGroup()
                .addComponent(logo_label, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(header_label, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        header_panelLayout.setVerticalGroup(
            header_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(header_panelLayout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addComponent(header_label)
                .addContainerGap())
            .addComponent(logo_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(header_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(body_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(header_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(body_panel, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void login_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login_buttonActionPerformed
        // TODO add your handling code here:
        
        //Hide error messages
        accnum_error.setVisible(false);
        pin_error.setVisible(false);
        
        
        //Declaration
        int accnum=0,//Stores account number
            pin=0,//Stores pin number
            foundindex=-1;//Stores row index of entered account number
        
        String strpin=new String(pin_field.getPassword());//Converts char array value from pin input to string
        
        //Flags for validation
        boolean fieldsValid=true,dataValid=true,accnumFound=false,pinFound=false;
        
        
        //Account Number Validation
        if(accnum_field.getText().isBlank()){
            accnum_error.setText("Missing Value");
            accnum_error.setVisible(true);
            fieldsValid=false;
        }
        else if(accnum_field.getText().length()==6){
            try{
                accnum=Integer.parseInt(accnum_field.getText());
            }
            catch(NumberFormatException e){
                accnum_error.setText("Must be numeric");
                accnum_error.setVisible(true);
                fieldsValid=false;
            }
        }
        else{
            accnum_error.setText("Must be 6 digits");
            accnum_error.setVisible(true);
            fieldsValid=false;
        }
        
        //Pin Validation
        if(strpin.isBlank()){
            pin_error.setText("Missing Value");
            pin_error.setVisible(true);
            fieldsValid=false;
        }
        else if(strpin.length()==4){
            try{
                pin=Integer.parseInt(strpin);
            }
            catch(Exception e){
                pin_error.setText("Must be numeric");
                pin_error.setVisible(true);
                fieldsValid=false;
            }
        }
        else{
            pin_error.setText("Must be 4 digits");
            pin_error.setVisible(true);
            fieldsValid=false;
        }
        
        //Checks if all fields are valid using boolean flag
        if(fieldsValid){
            //Matching entered values to database
            
            //Loops through each row of the table
            for(int i=0;i<dataobj.details_table.getRowCount();i++){
                
                //Checks whether accnum is found in the current row
                if(accnum_field.getText().equals(dataobj.details_table.getValueAt(i, 1).toString())){
                    //If found:
                    accnumFound=true;//sets accnumFound flag to true
                    foundindex=i;//stores row containing the matching Account Number
                    
                    //Checks if pin is found in the same row as accnum
                    if(strpin.equals(dataobj.details_table.getValueAt(foundindex, 2).toString())){
                        pinFound=true;
                    }
                    break;
                }
                
            }
            
            
            
            
            
            //Shows error labels for the appropriate errors
            if(accnumFound==false){
                accnum_error.setText("Account Number not found");
                accnum_error.setVisible(true);
                dataValid=false;
            }
            
            if(pinFound==false){
                pin_error.setText("Pin not found");
                pin_error.setVisible(true);
                dataValid=false;
            }
            
            
            //Final check whether both data were found in the table
            if(dataValid){
                accnum_field.setText("");
                pin_field.setText("");
                if(accnum==999999 && pin==1234){//Check if using manager account details
                    new ManagementControl().setVisible(true);//If true, proceeds to management control
                    dispose();
                }
                else{//Else, proceed to customer menu
                    new Home(foundindex).setVisible(true);
                    dispose();
                }
            }
            else{
                
                pin_field.setText("");//Clear pin field
                
                //Display error message and attempts remaining
                JOptionPane.showMessageDialog(this, "Details not found, please enter correct details or register.\nAttempts Remaining: "+(3-attempts), "Remaining attempts",JOptionPane.ERROR_MESSAGE);
                attempts++;//Increments failed attempts by 1
                
            }
            
            
            
            
        }
        else{
            //Clear all fields
            pin_field.setText("");
            
            attempts++;//If not, increments failed attempts by 1
            
            JOptionPane.showMessageDialog(this, "Invalid Login, Attempts Remaining: "+(3-attempts), "Remaining attempts",JOptionPane.ERROR_MESSAGE);
        }
        
        //Check failed attempts
        if(attempts>=3){
            //Simulate card ejection
            JOptionPane.showMessageDialog(this, "Too many failed login attempts, Card has been ejected", "Too many attempts",JOptionPane.ERROR_MESSAGE);
            new Welcome().setVisible(true);
            dispose();
        }
        
        
        
        
        
        
    }//GEN-LAST:event_login_buttonActionPerformed

    private void signup_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signup_buttonActionPerformed
        // TODO add your handling code here:
        //Move to Signup Page
        new Signup().setVisible(true);
        dispose();
    }//GEN-LAST:event_signup_buttonActionPerformed

    private void back_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_buttonActionPerformed
        // TODO add your handling code here:
        //Back to Welcome Page
        new Welcome().setVisible(true);
        dispose();
    }//GEN-LAST:event_back_buttonActionPerformed

    @SuppressWarnings("empty-statement")
    private void forgotaccnum_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_forgotaccnum_buttonActionPerformed
        // TODO add your handling code here:
        
        //Declaration
        boolean inputValid=true;//Flag to check whether input is valid
        int num=0,foundindex=-1;
        String input="";//Stores input
        
        do{//Loop to repeatedly ask for user input until valid
            inputValid=true;
            try{
                input=JOptionPane.showInputDialog(this,"Enter your phone number (Ex. 05****: ").replace(" ", "");//Prompt user for input and store in 'input'
            }
            catch(Exception e){
                break;//Break out of loop in case of error
            }
            
            //Input validation
            try{
                num=Integer.parseInt(input);
            }
            catch(NumberFormatException e){
                inputValid=false;
                JOptionPane.showMessageDialog(this,"Must be numeric");
                continue;
            }
            
            if(input.charAt(0)!='0'){
                inputValid=false;
                JOptionPane.showMessageDialog(this,"Must start with 0");
                continue;
            }
            
            if(input.length()!=10){
                inputValid=false;
                JOptionPane.showMessageDialog(this,"Must be 10 digits");
            }
            
        }while(!inputValid);
        
        //Final Check whether input was valid
        if(inputValid){
            
            //Loops through each row of the database to find entered contact number
            for(int j=0;j<dataobj.details_table.getRowCount();j++){
                if(input.equals(dataobj.details_table.getValueAt(j, 3).toString().replace(" ",""))){
                    foundindex=j;//If found, stores row index
                }
            }
            
            //Checks whether contact number was found in database
            if(foundindex!=-1){
                //Shows SMS screen
                new SMS(foundindex).setVisible(true);
                dispose();
            }
            else{
                JOptionPane.showMessageDialog(this, "Phone number not found");
            }
            
        }
    }//GEN-LAST:event_forgotaccnum_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel accnum_error;
    private javax.swing.JTextField accnum_field;
    private javax.swing.JLabel accnum_label;
    private javax.swing.JButton back_button;
    private javax.swing.JPanel body_panel;
    private javax.swing.JButton forgotaccnum_button;
    private javax.swing.JLabel header_label;
    private javax.swing.JPanel header_panel;
    private javax.swing.JButton login_button;
    private javax.swing.JLabel logo_label;
    private javax.swing.JLabel pin_error;
    private javax.swing.JPasswordField pin_field;
    private javax.swing.JLabel pin_label;
    private javax.swing.JButton signup_button;
    // End of variables declaration//GEN-END:variables
}
