

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Maryann
 */
public class ManagementControl extends javax.swing.JFrame {

    /**
     * Creates new form ManagementControl
     */
    private final Database dataobj=new Database();
    
    public ManagementControl() {
        initComponents();
        setTitle("Management Control");
        setDefaultCloseOperation(this.DO_NOTHING_ON_CLOSE);
        
        //Set Logo
        logo_label.setIcon(dataobj.CreateIcon(logo_label));
        
    }

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        main_panel = new javax.swing.JPanel();
        viewhistory_button = new javax.swing.JButton();
        shutdown_button = new javax.swing.JButton();
        header_panel = new javax.swing.JPanel();
        header_label = new javax.swing.JLabel();
        logo_label = new javax.swing.JLabel();
        menubar = new javax.swing.JMenuBar();
        window_menu = new javax.swing.JMenu();
        window_exit = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        main_panel.setBackground(new java.awt.Color(115, 115, 115));

        viewhistory_button.setBackground(new java.awt.Color(121, 81, 168));
        viewhistory_button.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        viewhistory_button.setForeground(new java.awt.Color(35, 35, 35));
        viewhistory_button.setText("View History");
        viewhistory_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewhistory_buttonActionPerformed(evt);
            }
        });

        shutdown_button.setBackground(new java.awt.Color(121, 81, 168));
        shutdown_button.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        shutdown_button.setForeground(new java.awt.Color(154, 22, 22));
        shutdown_button.setText("Shutdown");
        shutdown_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shutdown_buttonActionPerformed(evt);
            }
        });

        header_panel.setBackground(new java.awt.Color(105, 54, 158));

        header_label.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        header_label.setForeground(new java.awt.Color(204, 204, 204));
        header_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        header_label.setText("Manager Control");

        javax.swing.GroupLayout header_panelLayout = new javax.swing.GroupLayout(header_panel);
        header_panel.setLayout(header_panelLayout);
        header_panelLayout.setHorizontalGroup(
            header_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, header_panelLayout.createSequentialGroup()
                .addComponent(logo_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(header_label)
                .addGap(20, 20, 20))
        );
        header_panelLayout.setVerticalGroup(
            header_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(header_panelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(header_label, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
            .addComponent(logo_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout main_panelLayout = new javax.swing.GroupLayout(main_panel);
        main_panel.setLayout(main_panelLayout);
        main_panelLayout.setHorizontalGroup(
            main_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(header_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(main_panelLayout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(main_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(viewhistory_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(shutdown_button, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(80, Short.MAX_VALUE))
        );
        main_panelLayout.setVerticalGroup(
            main_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(main_panelLayout.createSequentialGroup()
                .addComponent(header_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(viewhistory_button, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(shutdown_button, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        menubar.setBackground(new java.awt.Color(152, 152, 152));

        window_menu.setBackground(new java.awt.Color(152, 152, 152));
        window_menu.setForeground(new java.awt.Color(35, 35, 35));
        window_menu.setText("Window");

        window_exit.setText("Exit");
        window_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                window_exitActionPerformed(evt);
            }
        });
        window_menu.add(window_exit);

        menubar.add(window_menu);

        setJMenuBar(menubar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(main_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(main_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void window_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_window_exitActionPerformed
        // TODO add your handling code here:
        new Welcome().setVisible(true);
        dataobj.setVisible(false);
        dispose();
    }//GEN-LAST:event_window_exitActionPerformed

    private void shutdown_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shutdown_buttonActionPerformed
        // TODO add your handling code here:
        for(int i=0;i<dataobj.dailytrans_table.getRowCount();i++){
            for(int j=1;j<dataobj.dailytrans_table.getColumnCount();j++){
                dataobj.dailytrans_table.setValueAt(0, i, j);
            }
        }
        dataobj.ExportDatabase();
        System.exit(0);
    }//GEN-LAST:event_shutdown_buttonActionPerformed

    private void viewhistory_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewhistory_buttonActionPerformed
        // TODO add your handling code here:
        dataobj.setVisible(true);
        dataobj.setLocationRelativeTo(null);

    }//GEN-LAST:event_viewhistory_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManagementControl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManagementControl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManagementControl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManagementControl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManagementControl().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel header_label;
    private javax.swing.JPanel header_panel;
    private javax.swing.JLabel logo_label;
    private javax.swing.JPanel main_panel;
    private javax.swing.JMenuBar menubar;
    private javax.swing.JButton shutdown_button;
    private javax.swing.JButton viewhistory_button;
    private javax.swing.JMenuItem window_exit;
    private javax.swing.JMenu window_menu;
    // End of variables declaration//GEN-END:variables
}
