import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.Random;
import javax.swing.ImageIcon;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Maryann
 */
public class Signup extends javax.swing.JFrame {

    /**
     * Creates new form Signup
     */
    
    
    
    private final Database dataobj=new Database();//Create database object
    
    //Declare and initialize model objects for each database table
    private final DefaultTableModel model,dailytransmodel,totaltransmodel;
    
    public Signup() {
        initComponents();
        setTitle("Signup");//Set window title
        setDefaultCloseOperation(this.DO_NOTHING_ON_CLOSE);//Prevent system shutdown from clicking 'X' button
        
        //Add Logo
        ImageIcon my_img=new ImageIcon(Toolkit.getDefaultToolkit().getImage("./Resources\\Nexus_Logo_Round.png"));//Take given image and put it in my_img object
        Image img=my_img.getImage();
        img=img.getScaledInstance(logo_label.getWidth(),logo_label.getHeight(),Image.SCALE_SMOOTH);
        ImageIcon i=new ImageIcon(img);
        logo_label.setIcon(i);
        
        //Hide error labels
        name_error.setVisible(false);
        contact_error.setVisible(false);
        pin_error.setVisible(false);
        
        
        
        model=(DefaultTableModel) dataobj.details_table.getModel();
        dailytransmodel=(DefaultTableModel) dataobj.dailytrans_table.getModel();
        totaltransmodel=(DefaultTableModel) dataobj.totaltrans_table.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        body_panel = new javax.swing.JPanel();
        contact_error = new javax.swing.JLabel();
        pin_error = new javax.swing.JLabel();
        name_field = new javax.swing.JTextField();
        pin_field = new javax.swing.JTextField();
        name_label = new javax.swing.JLabel();
        contact_label = new javax.swing.JLabel();
        pin_label = new javax.swing.JLabel();
        signup_button = new javax.swing.JButton();
        name_error = new javax.swing.JLabel();
        back_button = new javax.swing.JButton();
        contact_field = new javax.swing.JFormattedTextField();
        contact_combo = new javax.swing.JComboBox<>();
        header_panel = new javax.swing.JPanel();
        header_label = new javax.swing.JLabel();
        logo_label = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        body_panel.setBackground(new java.awt.Color(115, 115, 115));

        contact_error.setForeground(new java.awt.Color(154, 22, 22));
        contact_error.setText("Missing value");

        pin_error.setForeground(new java.awt.Color(154, 22, 22));
        pin_error.setText("Missing value");

        name_field.setBackground(new java.awt.Color(152, 152, 152));

        pin_field.setBackground(new java.awt.Color(152, 152, 152));

        name_label.setBackground(new java.awt.Color(35, 35, 35));
        name_label.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        name_label.setForeground(new java.awt.Color(35, 35, 35));
        name_label.setLabelFor(name_field);
        name_label.setText("Name:");

        contact_label.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        contact_label.setForeground(new java.awt.Color(35, 35, 35));
        contact_label.setLabelFor(contact_field);
        contact_label.setText("Contact Number:");

        pin_label.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        pin_label.setForeground(new java.awt.Color(35, 35, 35));
        pin_label.setLabelFor(pin_field);
        pin_label.setText("PIN:");

        signup_button.setBackground(new java.awt.Color(121, 81, 168));
        signup_button.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        signup_button.setForeground(new java.awt.Color(35, 35, 35));
        signup_button.setText("SIGN UP");
        signup_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signup_buttonActionPerformed(evt);
            }
        });

        name_error.setForeground(new java.awt.Color(154, 22, 22));
        name_error.setText("Missing value");

        back_button.setBackground(new java.awt.Color(121, 81, 168));
        back_button.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        back_button.setForeground(new java.awt.Color(35, 35, 35));
        back_button.setText("BACK");
        back_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_buttonActionPerformed(evt);
            }
        });

        contact_field.setBackground(new java.awt.Color(152, 152, 152));
        try {
            contact_field.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        contact_combo.setBackground(new java.awt.Color(152, 152, 152));
        contact_combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---", "050", "052", "054", "055", "056", "057", "058" }));
        contact_combo.setOpaque(false);
        contact_combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contact_comboActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout body_panelLayout = new javax.swing.GroupLayout(body_panel);
        body_panel.setLayout(body_panelLayout);
        body_panelLayout.setHorizontalGroup(
            body_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(body_panelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(body_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pin_field)
                    .addComponent(name_field)
                    .addGroup(body_panelLayout.createSequentialGroup()
                        .addComponent(signup_button, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(back_button, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(body_panelLayout.createSequentialGroup()
                        .addGroup(body_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pin_label, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pin_error, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(name_error)
                            .addComponent(name_label, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(contact_error, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(contact_label))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, body_panelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(contact_combo, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(contact_field, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        body_panelLayout.setVerticalGroup(
            body_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(body_panelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(name_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(name_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(name_error)
                .addGap(24, 24, 24)
                .addComponent(contact_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(body_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(contact_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(contact_combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contact_error)
                .addGap(24, 24, 24)
                .addComponent(pin_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pin_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pin_error)
                .addGap(18, 18, 18)
                .addGroup(body_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(signup_button, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(back_button, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        header_panel.setBackground(new java.awt.Color(105, 54, 158));
        header_panel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(105, 54, 158), 5, true));

        header_label.setBackground(new java.awt.Color(204, 204, 204));
        header_label.setFont(new java.awt.Font("Segoe UI Emoji", 1, 36)); // NOI18N
        header_label.setForeground(new java.awt.Color(204, 204, 204));
        header_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        header_label.setText("Signup");

        javax.swing.GroupLayout header_panelLayout = new javax.swing.GroupLayout(header_panel);
        header_panel.setLayout(header_panelLayout);
        header_panelLayout.setHorizontalGroup(
            header_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, header_panelLayout.createSequentialGroup()
                .addComponent(logo_label, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(header_label)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        header_panelLayout.setVerticalGroup(
            header_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, header_panelLayout.createSequentialGroup()
                .addGap(0, 14, Short.MAX_VALUE)
                .addComponent(header_label, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(logo_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(body_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(header_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(header_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(body_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void signup_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signup_buttonActionPerformed
        // TODO add your handling code here:
        //Hide Error Labels
        name_error.setVisible(false);
        contact_error.setVisible(false);
        pin_error.setVisible(false);
        
        //Prevent user from typing in contact field without selecting a value
        if(contact_combo.getSelectedIndex()==0){
            contact_field.setEditable(false);
        }
        
        
        //Declaration and initialization
        String name=name_field.getText();//Stores name input
        int accnum=0,pin=0;//Stores account number and pin input
        boolean fieldsValid=true,accnumGenerated=false;
        
        //Name Validation
        //Checks if empty
        if(name.isEmpty()){
            name_error.setText("Missing Value");
            name_error.setVisible(true);
            fieldsValid=false;
        }
        else{//Checks if numeric
            for(int i=0;i<name.length();i++){
                if(!((Character.isAlphabetic(name.charAt(i)))||(Character.isSpaceChar(name.charAt(i))))){
                    name_error.setText("Invalid Name");
                    name_error.setVisible(true);
                    fieldsValid=false;
                    break;
                }
            }
        }
        
        //Checks if name is taken
        for(int j=0;j<dataobj.details_table.getRowCount();j++){
            if(name.equals(dataobj.details_table.getValueAt(j,0))){
                JOptionPane.showMessageDialog(this, "You have already registered\nIf you've forgotten your account number, please navigate to login page", "Name Taken",JOptionPane.ERROR_MESSAGE);
                name_error.setText("Name Taken");
                name_error.setVisible(true);
                fieldsValid=false;
            }
        }
        
        //Contact Number Validation
        if(contact_combo.getSelectedIndex()==0){
            contact_error.setText("Missing Value");
            contact_error.setVisible(true);
            fieldsValid=false;
        }
        else if(contact_field.getText().substring(3).isBlank()){
            contact_error.setText("Missing Value");
            contact_error.setVisible(true);
            fieldsValid=false;
        }
        
        //Checks if contact number is taken
        for(int j=0;j<dataobj.details_table.getRowCount();j++){
            if(contact_field.getText().equals(dataobj.details_table.getValueAt(j,3))){
                JOptionPane.showMessageDialog(this, "You have already registered\nIf you've forgotten your account number, please navigate to login page", "Name Taken",JOptionPane.ERROR_MESSAGE);
                contact_error.setText("Contact Number Taken");
                contact_error.setVisible(true);
                fieldsValid=false;
            }
        }
        
        
        
        //Pin Validation
        if(pin_field.getText().isBlank()){
            pin_error.setText("Missing Value");
            pin_error.setVisible(true);
            fieldsValid=false;
        }
        else if(pin_field.getText().length()==4){
            try{
                pin=Integer.parseInt(pin_field.getText());
            }
            catch(Exception e){
                pin_error.setText("Must be numeric");
                pin_error.setVisible(true);
                fieldsValid=false;
            }
            for(int k=0;k<dataobj.details_table.getRowCount();k++){
                if(pin_field.getText().equals(dataobj.details_table.getValueAt(k, 2))){
                    pin_error.setText("PIN Taken");
                    pin_error.setVisible(true);
                    fieldsValid=false;
                }
            }
        }
        else{
            pin_error.setText("Must be 4 digits");
            pin_error.setVisible(true);
            fieldsValid=false;
        }
        
        //Generate account number
        do{
            Random rand=new Random();
            accnum=100000+rand.nextInt(900000);
            accnumGenerated=true;
            for(int l=0;l<dataobj.details_table.getRowCount();l++){
                if(String.format("%d", accnum).equals(dataobj.details_table.getValueAt(l, 3))){
                    accnumGenerated=false;
                }
            }
        }while(accnumGenerated==false);
        
        
        
        
        //Checks if all fields are valid
        if(fieldsValid){
            
            name=name.substring(0,1).toUpperCase()+name.substring(1);//Capitalize first letter of name
            
            //Update Databases
            //Transaction Database
            dailytransmodel.addRow(new Object[]{accnum,0,0,0,0});
            dataobj.dailytrans_table.setModel(dailytransmodel);
            
            totaltransmodel.addRow(new Object[]{accnum,0,0,0,0});
            dataobj.totaltrans_table.setModel(totaltransmodel);
            
            //Main Database
            model.addRow(new Object[]
            {name,accnum,pin,contact_field.getText(),0,0.00});
            
            dataobj.details_table.setModel(model);//Update table model
            
            dataobj.ExportDatabase();
            
            
            JOptionPane.showMessageDialog(this,"Signup Successful!\nYour account number is: "+accnum,"SUCCESS",JOptionPane.PLAIN_MESSAGE);
            
            
            
            
            
            //Clear all fields
            name_field.setText("");
            contact_combo.setSelectedIndex(0);
            pin_field.setText("");
            
            
            //Return to Login Screen
            new Login().setVisible(true);
            setVisible(false);
        }
        
        
        
        
    }//GEN-LAST:event_signup_buttonActionPerformed

    private void back_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_buttonActionPerformed
        // TODO add your handling code here:
        //Back to Login Page
        new Login().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_back_buttonActionPerformed

    private void contact_comboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contact_comboActionPerformed
        // TODO add your handling code here:
        
        //Sets starting 3 digits of contact field depending on combo box choice
        if(contact_combo.getSelectedIndex()==0){
            try {
                contact_field.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("")));
                contact_field.setEditable(false);
            } catch (java.text.ParseException ex) {
                ex.printStackTrace();
            }
        }
        else{
            try {
                contact_field.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter(contact_combo.getSelectedItem()+" ### ####")));
                contact_field.setEditable(true);
            } catch (java.text.ParseException ex) {
                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_contact_comboActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Signup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back_button;
    private javax.swing.JPanel body_panel;
    private javax.swing.JComboBox<String> contact_combo;
    private javax.swing.JLabel contact_error;
    private javax.swing.JFormattedTextField contact_field;
    private javax.swing.JLabel contact_label;
    private javax.swing.JLabel header_label;
    private javax.swing.JPanel header_panel;
    private javax.swing.JLabel logo_label;
    private javax.swing.JLabel name_error;
    private javax.swing.JTextField name_field;
    private javax.swing.JLabel name_label;
    private javax.swing.JLabel pin_error;
    private javax.swing.JTextField pin_field;
    private javax.swing.JLabel pin_label;
    private javax.swing.JButton signup_button;
    // End of variables declaration//GEN-END:variables
}
