import java.awt.Cursor;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.ImageIcon;



/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Maryann
 */
public class SMS extends javax.swing.JFrame {

    /**
     * Creates new form SMS
     */
    private final Database dataobj=new Database();
    
    public SMS(int foundindex) {
        initComponents();
        setTitle("Phone");
        setDefaultCloseOperation(this.DO_NOTHING_ON_CLOSE);
        
        //Hide button background and border
        back_button.setBorder(null);
        back_button.setContentAreaFilled(false);
        
        //Hide text area background and border
        jScrollPane1.setBorder(null);
        jScrollPane1.getViewport().setOpaque(false);
        
        //Set Profile Picture
        ImageIcon my_img=new ImageIcon(Toolkit.getDefaultToolkit().getImage("./Resources\\Nexus_Logo_Circle.png"));//Take given image and put it in my_img object
        Image img=my_img.getImage();
        img=img.getScaledInstance(logo_label.getWidth(),logo_label.getHeight(),Image.SCALE_SMOOTH);
        ImageIcon i=new ImageIcon(img);
        logo_label.setIcon(i);
        
        
        
        //Set Text Message
        sms_textarea.setText("Hi, "+dataobj.details_table.getValueAt(foundindex, 0).toString()
                    +"!  Your account number is: "+dataobj.details_table.getValueAt(foundindex, 1).toString());
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        main_panel = new javax.swing.JPanel();
        screen_panel = new javax.swing.JPanel();
        back_button = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        sms_textarea = new javax.swing.JTextArea();
        code_label = new javax.swing.JLabel();
        logo_label = new javax.swing.JLabel();
        sender_label = new javax.swing.JLabel();
        screen_label = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        screen_panel.setLayout(null);

        back_button.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        back_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_buttonActionPerformed(evt);
            }
        });
        screen_panel.add(back_button);
        back_button.setBounds(3, 15, 50, 40);

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        sms_textarea.setEditable(false);
        sms_textarea.setBackground(new java.awt.Color(162, 203, 129));
        sms_textarea.setColumns(20);
        sms_textarea.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        sms_textarea.setForeground(new java.awt.Color(51, 51, 55));
        sms_textarea.setLineWrap(true);
        sms_textarea.setRows(5);
        sms_textarea.setWrapStyleWord(true);
        sms_textarea.setBorder(null);
        jScrollPane1.setViewportView(sms_textarea);

        screen_panel.add(jScrollPane1);
        jScrollPane1.setBounds(30, 100, 160, 60);

        code_label.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        code_label.setForeground(new java.awt.Color(115, 115, 115));
        code_label.setText("Can't reply to this short code");
        screen_panel.add(code_label);
        code_label.setBounds(20, 505, 220, 18);
        screen_panel.add(logo_label);
        logo_label.setBounds(60, 10, 50, 50);

        sender_label.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        sender_label.setForeground(new java.awt.Color(115, 115, 115));
        sender_label.setText("Nexus");
        screen_panel.add(sender_label);
        sender_label.setBounds(120, 30, 60, 15);

        screen_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Nexus_SMS.png"))); // NOI18N
        screen_panel.add(screen_label);
        screen_label.setBounds(0, 0, 257, 553);

        javax.swing.GroupLayout main_panelLayout = new javax.swing.GroupLayout(main_panel);
        main_panel.setLayout(main_panelLayout);
        main_panelLayout.setHorizontalGroup(
            main_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(main_panelLayout.createSequentialGroup()
                .addComponent(screen_panel, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        main_panelLayout.setVerticalGroup(
            main_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(screen_panel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 553, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(main_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(main_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void back_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_buttonActionPerformed
        // TODO add your handling code here:
        new Login().setVisible(true);
        dispose();
    }//GEN-LAST:event_back_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SMS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SMS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SMS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SMS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SMS(0).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back_button;
    private javax.swing.JLabel code_label;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel logo_label;
    private javax.swing.JPanel main_panel;
    private javax.swing.JLabel screen_label;
    private javax.swing.JPanel screen_panel;
    private javax.swing.JLabel sender_label;
    public javax.swing.JTextArea sms_textarea;
    // End of variables declaration//GEN-END:variables
}
